# Generated by Django 6.0.3 on 2026-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
    ]
