# Generated by Django 6.0.3 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="units_in_pack",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
