# Generated by Django 6.0.3 on 2026-04-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0002_pack_units_in_pack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="size",
            name="category",
        ),
    ]
