# Generated by Django 6.0.3 on 2026-04-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('people', '0001_initial'),
        ('sales', '0001_initial'),
        ('usermgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawershift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdrawershift',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermgmt.store'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.cashdrawershift'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermgmt.store'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
